spring:
  cloud:
    stream:
      default: 
         producer: 
          useNativeEncoding: false
         consumer:  
          useNativeEncoding: false    
      bindings:
        input:
          destination: employee-details
          content-type: application/json
        output:
          destination: employee-details
          content-type: application/json
      kafka:
          binder:
            brokders: localhost:9092   

                           
